import type { Template, GeneratedFile } from '../types.js';
import { getRulesForTemplate } from './rules-content.js';

/**
 * Generates the 4 universal AI context rule files based on the selected template.
 *
 * - .cursorrules          → For Cursor IDE
 * - .windsurfrules        → For Windsurf IDE
 * - .github/copilot-instructions.md → For GitHub Copilot
 * - AI_INSTRUCTIONS.md    → For Claude Code, Antigravity, and other CLI agents
 */
export function generateAIRuleFiles(template: Template): GeneratedFile[] {
  const rules = getRulesForTemplate(template);

  const templateLabel =
    template === 'nextjs'
      ? 'Next.js App Router'
      : template === 'fastapi'
        ? 'Python FastAPI'
        : 'Node.js Express API';

  const cursorContent = `# Cursor AI Rules — ${templateLabel}
# Auto-generated by prompt-scaffold
# These rules ensure Cursor AI writes code that follows this project's architecture.

${rules}
`;

  const windsurfContent = `# Windsurf AI Rules — ${templateLabel}
# Auto-generated by prompt-scaffold
# These rules ensure Windsurf AI writes code that follows this project's architecture.

${rules}
`;

  const copilotContent = `# GitHub Copilot Instructions — ${templateLabel}

> Auto-generated by [prompt-scaffold](https://github.com/prompt-scaffold/prompt-scaffold).
> These instructions ensure GitHub Copilot writes code that follows this project's architecture.

---

${rules}
`;

  const masterContent = `# AI Instructions — ${templateLabel}

> **This is the master AI context file for this project.**
> Auto-generated by [prompt-scaffold](https://github.com/prompt-scaffold/prompt-scaffold).
>
> If you are an AI assistant (Claude Code, Antigravity, Aider, Continue, or any other tool),
> read this file FIRST before writing any code. It contains the architectural rules,
> coding standards, and best practices for this specific project.

---

${rules}

---

## How to Use This File

- **Claude Code / Antigravity**: This file is automatically read when placed in the project root.
- **Cursor**: See \`.cursorrules\` (same content, Cursor-specific format).
- **Windsurf**: See \`.windsurfrules\` (same content, Windsurf-specific format).
- **GitHub Copilot**: See \`.github/copilot-instructions.md\`.
- **Other Tools**: Point your AI assistant to this file for full project context.
`;

  return [
    { path: '.cursorrules', content: cursorContent },
    { path: '.windsurfrules', content: windsurfContent },
    { path: '.github/copilot-instructions.md', content: copilotContent },
    { path: 'AI_INSTRUCTIONS.md', content: masterContent },
  ];
}
