import type { Template, GeneratedFile } from '../types.js';
import { TEMPLATE_LABELS } from '../types.js';
import { getRulesForTemplate } from './rules-content.js';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Reads the optional .aicustomrules file from a project directory.
 * Returns the content if found, or null.
 */
function readCustomRules(projectRoot: string): string | null {
  const customRulesPath = path.join(projectRoot, '.aicustomrules');
  if (existsSync(customRulesPath)) {
    try {
      const content = readFileSync(customRulesPath, 'utf-8').trim();
      if (content.length > 0) {
        return content;
      }
    } catch {
      // Ignore read errors
    }
  }
  return null;
}

/**
 * Generates a default .aicustomrules template file.
 */
export function generateCustomRulesTemplate(): GeneratedFile {
  return {
    path: '.aicustomrules',
    content: `# Custom AI Rules
# Add your team-specific conventions below.
# These rules will be appended to ALL generated AI context files
# when you run \`prompt-scaffold --inject\`.
#
# Examples:
# - Use Zustand for state management, NOT Redux
# - All API calls go through src/services/ using the custom fetchClient
# - Component files use PascalCase: MyComponent.tsx
# - Test files are co-located: MyComponent.test.tsx
`,
  };
}

/**
 * Generates the 4 universal AI context rule files based on the selected template.
 * Optionally appends custom rules from .aicustomrules if present.
 *
 * - .cursorrules          → For Cursor IDE
 * - .windsurfrules        → For Windsurf IDE
 * - .github/copilot-instructions.md → For GitHub Copilot
 * - AI_INSTRUCTIONS.md    → For Claude Code, Antigravity, and other CLI agents
 */
export function generateAIRuleFiles(
  template: Template,
  projectRoot?: string
): GeneratedFile[] {
  const rules = getRulesForTemplate(template);

  const templateLabel = TEMPLATE_LABELS[template];

  // Read custom rules if project root is provided
  let customSection = '';
  if (projectRoot) {
    const customRules = readCustomRules(projectRoot);
    if (customRules) {
      customSection = `\n\n---\n\n## Project-Specific Rules (from .aicustomrules)\n\n${customRules}\n`;
    }
  }

  const cursorContent = `# Cursor AI Rules — ${templateLabel}
# Auto-generated by prompt-scaffold
# These rules ensure Cursor AI writes code that follows this project's architecture.

${rules}${customSection}
`;

  const windsurfContent = `# Windsurf AI Rules — ${templateLabel}
# Auto-generated by prompt-scaffold
# These rules ensure Windsurf AI writes code that follows this project's architecture.

${rules}${customSection}
`;

  const copilotContent = `# GitHub Copilot Instructions — ${templateLabel}

> Auto-generated by [prompt-scaffold](https://github.com/KhotJarb/prompt-scaffold).
> These instructions ensure GitHub Copilot writes code that follows this project's architecture.

---

${rules}${customSection}
`;

  const masterContent = `# AI Instructions — ${templateLabel}

> **This is the master AI context file for this project.**
> Auto-generated by [prompt-scaffold](https://github.com/KhotJarb/prompt-scaffold).
>
> If you are an AI assistant (Claude Code, Antigravity, Aider, Continue, or any other tool),
> read this file FIRST before writing any code. It contains the architectural rules,
> coding standards, and best practices for this specific project.

---

${rules}${customSection}

---

## How to Use This File

- **Claude Code / Antigravity**: This file is automatically read when placed in the project root.
- **Cursor**: See \`.cursorrules\` (same content, Cursor-specific format).
- **Windsurf**: See \`.windsurfrules\` (same content, Windsurf-specific format).
- **GitHub Copilot**: See \`.github/copilot-instructions.md\`.
- **Other Tools**: Point your AI assistant to this file for full project context.
`;

  return [
    { path: '.cursorrules', content: cursorContent },
    { path: '.windsurfrules', content: windsurfContent },
    { path: '.github/copilot-instructions.md', content: copilotContent },
    { path: 'AI_INSTRUCTIONS.md', content: masterContent },
  ];
}
