import type { Template, GeneratedFile } from './types.js';

/**
 * Generates GitHub Actions CI workflow file tailored to the project's template.
 */
export function generateCICDFiles(template: Template): GeneratedFile[] {
  const workflow = getGitHubActionsWorkflow(template);
  return [
    {
      path: '.github/workflows/ci.yml',
      content: workflow,
    },
  ];
}

function getGitHubActionsWorkflow(template: Template): string {
  switch (template) {
    case 'nextjs':
      return `# GitHub Actions CI — Next.js
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
`;

    case 'react-vite':
      return `# GitHub Actions CI — React + Vite
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint src/

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build

      - name: Preview build output
        run: ls -la dist/
`;

    case 'express':
      return `# GitHub Actions CI — Express API
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint src/

      - name: Type check
        run: npx tsc --noEmit

      - name: Build
        run: npm run build
`;

    case 'nestjs':
      return `# GitHub Actions CI — NestJS API
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js \${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: \${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx eslint src/

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test
`;

    case 'fastapi':
      return `# GitHub Actions CI — FastAPI
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python \${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dev tools
        run: pip install ruff mypy pytest pytest-asyncio httpx

      - name: Lint with ruff
        run: ruff check .

      - name: Format check with ruff
        run: ruff format --check .

      - name: Type check with mypy
        run: mypy app/ --ignore-missing-imports

      - name: Test
        run: pytest -v
`;

    case 'django':
      return `# GitHub Actions CI — Django
# Auto-generated by prompt-scaffold

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.12']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python \${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: \${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install dev tools
        run: pip install ruff mypy pytest pytest-django

      - name: Lint with ruff
        run: ruff check .

      - name: Format check with ruff
        run: ruff format --check .

      - name: Run migrations check
        run: python manage.py migrate --check --dry-run
        env:
          SECRET_KEY: test-secret-key
          DEBUG: 'True'

      - name: Test
        run: python manage.py test
        env:
          SECRET_KEY: test-secret-key
          DEBUG: 'True'
`;
  }
}
